name: Integration Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  integration-testing:
    name: Integration Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.THIS_PAT }}
      - name: Test action
        id: test-action
        # test with the local checkout of the action
        uses: ./
        with:
          template: https://github.com/cjolowicz/cookiecutter-hypermodern-python
          cookiecutterValues: '{
            "project_name": "integration-test"
          }'
      - name: Check that our created template exists
        id: check_files
        uses: andstor/file-existence-action@v1.1.0
        with:
          files: "integration-test"
      - name: Check ls
        run: |
          ls
      - name: Check check_files
        run: |
          test "${{ steps.check_files.outputs.files_exists }}" == "true"
      - name: Check outputs
        run: |
          test "${{ steps.test-action.outputs.outputDir }}" == "/github/workspace/integration-test"
